09:30:26 [32mINFO[0m Model status:

Model    Controller                Cloud/Region        Version  SLA          Timestamp
testing  github-pr-fce5b-microk8s  microk8s/localhost  3.6.11   unsupported  09:30:26Z

App             Version  Status  Scale  Charm           Channel  Rev  Address        Exposed  Message
fastapi-k8s              active      1  fastapi-k8s                0  10.152.183.70  no       
postgresql-k8s  14.19    active      1  postgresql-k8s  14/edge  684  10.152.183.64  no       

Unit               Workload  Agent  Address       Ports  Message
fastapi-k8s/0*     active    idle   10.1.181.138         
postgresql-k8s/0*  active    idle   10.1.181.140         Primary

09:30:26 [32mINFO[0m Juju error logs:

unit-fastapi-k8s-0: 09:28:46 ERROR unit.fastapi-k8s/0.juju-log database migration command ['bash', '-eo', 'pipefail', 'migrate.sh'] failed, stdout: , stderr: Traceback (most recent call last):
  File "/usr/bin/alembic", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/lib/python3.12/site-packages/alembic/config.py", line 1022, in main
    CommandLine(prog=prog).main(argv=argv)
  File "/lib/python3.12/site-packages/alembic/config.py", line 1012, in main
    self.run_cmd(cfg, options)
  File "/lib/python3.12/site-packages/alembic/config.py", line 946, in run_cmd
    fn(
  File "/lib/python3.12/site-packages/alembic/command.py", line 483, in upgrade
    script.run_env()
  File "/lib/python3.12/site-packages/alembic/script/base.py", line 545, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/lib/python3.12/site-packages/alembic/util/pyfiles.py", line 116, in load_python_file
    module = load_module_py(module_id, path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.12/site-packages/alembic/util/pyfiles.py", line 136, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/app/alembic/env.py", line 11, in <module>
    from app import Base, engine
  File "/app/app.py", line 64, in <module>
    engine = create_engine(os.environ["POSTGRESQL_DB_CONNECT_STRING"], echo=True)
                           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen os>", line 685, in __getitem__
KeyError: 'POSTGRESQL_DB_CONNECT_STRING'


09:30:26 [32mINFO[0m Forgetting model main...